import os
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go

from pyromof import helpers, measure_flexibility


def merge_scalars_from_scenarios(scenarios, RESULTS):
    """
    This script takes a list of scenario names and processes and joins their scalar data.
    The resulting dataframe has the following format:
    |variable |type  |{scenario_name_1}_value|{scenario_name_2}_value|
    """
    key_columns = ["variable", "type"]

    def rename_columns_for_scenario(df, scenario):
        return df.rename(
            columns={col: f"{scenario}" for col in df.columns if col not in key_columns}
        )

    cost_dataframes = []
    dataframes = []
    for scenario in scenarios:
        SCENARIO_RESULTS = os.path.join(RESULTS, scenario, "results")
        scalar_results = pd.read_csv(
            os.path.join(SCENARIO_RESULTS, "scalar_results.csv"), sep=";", index_col=0
        )
        dataframes.append(rename_columns_for_scenario(scalar_results, scenario))

        scalcosts = helpers.prepare_cost_scalars_for_plotting(
            SCENARIO_RESULTS, "scalar_results.csv", scenario
        )
        cost_dataframes.append(rename_columns_for_scenario(scalcosts, scenario))

    merged_cost_df = cost_dataframes[0].copy()
    merged_df = dataframes[0].copy()

    for df in cost_dataframes[1:]:
        merged_cost_df = pd.merge(merged_cost_df, df, on=key_columns, how="outer")
    # Remove rows in which all values are either 0 or NaN
    merged_cost_df = merged_cost_df[
        ~merged_cost_df.drop(columns=key_columns).fillna(0).eq(0).all(axis=1)
    ]

    for df in dataframes[1:]:
        merged_df = pd.merge(merged_df, df, on=key_columns, how="outer")

    print(merged_cost_df)
    print(merged_df)
    merged_df.to_csv(os.path.join(RESULTS, "merged_scalar_results.csv"), sep=";", index=False)
    return merged_cost_df


def plot_cost_scalars_comparison(multiscenario_scalcosts, scenarios, RESULTS):
    """
    Takes a table of the format generated by merge_scalars_from_scenarios
    and a list of scenarios plots one stacked bar plot
    of the scalars for each scenario side by side.
    """

    fig = go.Figure()

    for variable in multiscenario_scalcosts.variable:
        fig.add_trace(
            go.Bar(
                name=variable,
                x=scenarios,
                y=multiscenario_scalcosts.loc[
                    multiscenario_scalcosts["variable"] == variable, scenarios
                ].iloc[0, :],
                hoverinfo="name+y",
            )
        )

    # Add points for total
    for scenario in scenarios:
        total = multiscenario_scalcosts[scenario].sum()
        fig.add_trace(
            go.Scatter(
                x=[scenario],
                y=[total],
                mode="markers",
                marker_symbol="diamond",
                marker_color="black",
                marker=dict(size=15),
                hoverinfo="text+y",
                text=["Total"],
                name="Total",
            )
        )

    # Plot negative values below the x-axis
    fig.update_layout(barmode="relative")
    # Save plot as html
    fig.write_html(os.path.join(RESULTS, "cost_scalars.html"))


def compare_scenarios():
    ROOT_PATH = Path(__file__).parent.parent
    RESULTS = os.path.join(ROOT_PATH, "results")
    scenarios = ["scenario1", "scenario2"]
    # Check if the scenarios exist and if not explain how to select scenarios
    for scenario in scenarios:
        if not os.path.exists(os.path.join(RESULTS, scenario)):
            raise ValueError(
                f"Scenario {scenario} does not exist. Please select scenarios "
                f"that are present in the results folder and enter them at "
                f"the bottom of the script compare_scenarios.py."
            )

    multiscenario_scalcosts = merge_scalars_from_scenarios(scenarios, RESULTS)
    plot_cost_scalars_comparison(multiscenario_scalcosts, scenarios, RESULTS)
    measure_flexibility.measure_flexibility(scenarios)
